name: Build on Ubuntu Latest

on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - name: Install required packages
        run: sudo apt install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
      - name: build 
        run: cmake .; make
